### ISSUE TITLE
New version for opam

### ISSUE THREAD

**Issue by vogler** [cil-project/cil#2]
The latest version available in [opam](opam.ocamlpro.com) is 1.5.1.
It would be nice to have a more recent version in opam.
I forked [opam-repository](https://github.com/vogler/opam-repository/tree/master/packages/cil.1.5.1) and tried to add versions 1.6.0 and 1.7.0 based on 1.5.1.
For [1.6.0](https://github.com/vogler/opam-repository/commit/913aa098ba28b07e5ac5ea04421838ee5a3e3556) the library seems to work, but executing `cilly` fails with `Can't locate CilConfig.pm`.
For [1.7.0](https://github.com/vogler/opam-repository/commit/a43cb92b300edab65562da7d383f70449a4666fa) I'm stuck at `make install` which tries to install something to `/usr/local/bin`.
Can it be configured to install to the opam directory? Also, I don't know what to do with the dependency on perl-ExtUtils-MakeMaker.

**Comment by kerneis** [comment]
On Fri, Jun 14, 2013 at 08:55:58AM -0700, Ralf Vogler wrote:

> The latest version available in [opam](opam.ocamlpro.com) is 1.5.1.
>  It would be nice to have a more recent version in opam.

Agreed.

> For
> [1.7.0](https://github.com/vogler/opam-repository/commit/a43cb92b300edab65562da7d383f70449a4666fa)
> I'm stuck at `make install` which tries to install something to
> `/usr/local/bin`.

I'm working on 1.7.1 since a few days, with the goal to make it clean enough to
create an opam package easily, using ocamlbuild, etc.

> Can it be configured to install to the opam directory?

Have you tried ./configure --prefix=whatever ?  But I would expect opam to set
the variable automatically (looks like a missing feature).

> Also, I don't know what to do with the dependency on perl-ExtUtils-MakeMaker.

cilly requires perl.  I think we should just assume it is installed (configure
will fail otherwise anyway).

I'll have a look at your work as soon as I'm done refactoring that crazy build
system.

**Comment by kerneis** [comment]
CIL is now available in opam (in fact, it has been for a long time, I just forgot to close this bug).
