### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by afjoseph** [cil-project/cil#48]

**Comment by michael-schwarz** [comment]
There no longer seems to be active development of the original project, but there exist some forks by people still using it, e.g. ours: https://github.com/goblint/cil

Depending on what you are aiming to do, one of these forks might be helpful to you or not. Note however that e.g. for our fork we are not committed to and interested in maintaining all features upstream CIL provides (MSVC support, some of the extensions, ...) and have made some modifications to CIL that fit our specific usecase, that make our fork incompatible with the original CIL.

Not sure to what extent this applies to other forks as well.

**Comment by afjoseph** [comment]
@michael-schwarz That was very helpful. Many thanks for your answer. I'll keep this issue open for just a bit longer, just to get a few more answers and close it early next week.

**Comment by kerneis** [comment]
I haven't had time to maintain this project anymore since I left academia. I looked for other maintainers for none showed up. The offer still stands if anybody demonstrates enough interest.

Richard Jones is doing a good job as a Redhat maintainer at keeping the latest release compiling as the Ocaml compiler evolves. It's a good resource if you want to run projects based on the original CIL.

Unfortunately I stopped maintaining the project midway though a breaking change that would have made writing plugins easier (I even wrote one as a motivating example) but never polished it enough to release cil 2.0. As a result, the current head of the GitHub repository lacks documentation.

The Frama-C fork has long diverged from this project but may be your best bet if you want an actively maintained project based on CIL (with many more features). I didn't follow it recently, but I believe it handles C11 (CIL doesn't even handle all of C99) and some C++.

Let me know if you have more question, I'm happy to share my experience. Life just made it so that I don't have time for coding side projects anymore.

Gabriel

**Comment by afjoseph** [comment]
@kerneis Thank you for the very kind reply. The project is wonderful and looks pretty self-sufficient by itself now. I'll close this issue now. My experience in OCaml is quite poor, but it's getting there. When it becomes alright, I'll try my best to contribute here.

Thanks again.
